FROM resin/rpi-raspbian:latest
MAINTAINER Chris Deter <chris.deter@student.uni-luebeck.de>

# Install dependencies
RUN apt-get -q update && \
    apt-get -qy install curl ca-certificates \
	git-core oracle-java8-jdk build-essential \
	sudo wget 
# WiringPi
RUN git clone git://git.drogon.net/wiringPi && cd wiringPi &&  ./build

# PI4J
RUN curl -s get.pi4j.com | bash

ENTRYPOINT ["/bin/sh", "-c"]

#433Mhz (https://tutorials-raspberrypi.de/raspberry-pis-ueber-433mhz-funk-kommunizieren-lassen/)
#RUN git clone https://github.com/ninjablocks/433Utils.git --recursive && cd 433Utils/RPi_utils && make all

#librxtx-java

#EXPOSE 3000

# CMD java - jar raspisoftware-0.0.1-SNAPSHOT.jar
# ENTRYPOINT ["/bin/sh", "-c"]

#CMD ["gpio readall"]

#docker build -t unilubecktest .
#docker ps -a
#docker run -it --privileged unilubecktest bash 